"""Acceptance tests over the financial sample pack (opt-in: ``pytest -m acceptance``).

These run the REAL pipeline (`run_project` / `analyze_run`) over realistic,
domain-named models — complementary to the deterministic Phase-S unit corpus.
They are excluded from the default fast CI gate (see pyproject ``addopts``).

Offline determinism comes from the manifest/comment-driven FakeProvider responses
generated by ``tests/tools/gen_pack_responses.py`` (the pack expresses I/O only in
docstrings/comments, so the adapters alone can't recover the chain). The holdout
and live-LLM tests are env-gated and skip by default.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from docx import Document
from openpyxl import load_workbook

from modeltracex.analysis.orchestrator import analyze_run
from modeltracex.cli import run_project
from modeltracex.exporters.docx_report import SECTION_TITLES
from modeltracex.exporters.xlsx_workbook import SHEETS
from modeltracex.ingestion import assemble_models, read_path
from modeltracex.lineage.graph import LineageGraph
from modeltracex.llm.fake import FakeProvider
from modeltracex.state import ModelStatus

pytestmark = pytest.mark.acceptance

PACK = Path(__file__).parent / "sample_pack"


def _responses(group: str) -> dict[str, str]:
    """Load generated FakeProvider responses for a group, keyed by model label (stem)."""
    root = PACK / "fake_responses" / group
    return {p.stem: p.read_text(encoding="utf-8") for p in sorted(root.glob("*.json"))}


def _files(group: str, suffix: str) -> list[str]:
    return [str(p) for p in sorted((PACK / group).glob(f"*{suffix}"))]


# --------------------------------------------------------------------------- #
# Chain stitches end-to-end (the headline cross-model lineage asset)
# --------------------------------------------------------------------------- #
def test_chain_stitches_offline(tmp_path: Path) -> None:
    provider = FakeProvider(responses=_responses("chained"), default="{}")
    models = assemble_models([read_path(f) for f in _files("chained", ".py")])
    state = analyze_run(provider, models, run_id="pack_chain")

    graph = LineageGraph(state)
    paths = [[graph.name_of(n) for n in p] for p in graph.source_to_output_paths()]
    expected = json.loads((PACK / "expected_chain.json").read_text("utf-8"))["node_path"]
    assert expected in paths, f"chain not stitched; got {paths}"

    # Intermediate handoffs collapse to one node each (10 files → one linear path).
    roles = {t.name: t.role.value for t in state.tables}
    assert roles["raw_source.csv"] == "Source"
    assert roles["final_overlay_report.csv"] == "Output"
    assert roles["macro_variables.csv"] == "Intermediate"


# --------------------------------------------------------------------------- #
# The committed dev subset runs clean and exports valid artifacts
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("group, suffix", [("sas", ".sas"), ("python", ".py"), ("chained", ".py")])
def test_dev_subset_runs_clean(group: str, suffix: str, tmp_path: Path) -> None:
    provider = FakeProvider(responses=_responses(group), default="{}")
    files = _files(group, suffix)
    state, outputs = run_project(files, str(tmp_path / group), provider)

    assert len(state.models) == len(files)
    assert all(m.status is not ModelStatus.FAILED for m in state.models), (
        "a model failed unexpectedly"
    )

    docx = [o for o in outputs if o.endswith(".docx")]
    xlsx = [o for o in outputs if o.endswith(".xlsx")]
    assert docx and xlsx
    doc = Document(docx[0])
    assert [p.text for p in doc.paragraphs if p.style.name == "Heading 1"] == SECTION_TITLES
    assert load_workbook(xlsx[0]).sheetnames == [name for name, _ in SHEETS]


# --------------------------------------------------------------------------- #
# Post-build: the full out-of-tree pack (incl. holdout) at scale — env-gated
# --------------------------------------------------------------------------- #
def _holdout_pack() -> Path | None:
    raw = os.environ.get("MODELTRACEX_SAMPLE_PACK")
    if not raw:
        return None
    p = Path(raw)
    return p if p.exists() else None


@pytest.mark.skipif(_holdout_pack() is None, reason="MODELTRACEX_SAMPLE_PACK not set")
def test_holdout_scale(tmp_path: Path) -> None:
    pack = _holdout_pack()
    assert pack is not None
    sas_files = [str(p) for p in sorted((pack / "sas").glob("*.sas"))]
    state, _ = run_project(sas_files, str(tmp_path / "holdout_sas"), FakeProvider(default="{}"))
    assert len(state.models) == len(sas_files) >= 8
    assert all(m.status is not ModelStatus.FAILED for m in state.models)
    # SAS adapter recovers the work.* dataset pattern even with an empty LLM response.
    assert any(t.name.startswith("work.") for t in state.tables)


# --------------------------------------------------------------------------- #
# Post-build: accuracy against the manifest/CHAIN oracle with a live provider
# --------------------------------------------------------------------------- #
@pytest.mark.skipif(
    os.environ.get("MODELTRACEX_PROVIDER") != "anthropic"
    or not os.environ.get("MODELTRACEX_ANTHROPIC_API_KEY"),
    reason="live anthropic provider not configured",
)
def test_live_llm_chain_accuracy(tmp_path: Path) -> None:  # pragma: no cover - manual/nightly
    from modeltracex.config import get_settings
    from modeltracex.llm.provider import build_provider

    provider = build_provider(get_settings())
    models = assemble_models([read_path(f) for f in _files("chained", ".py")[:3]])
    state = analyze_run(provider, models, run_id="pack_live")
    # Loose accuracy check: the live model should recover at least one real chain file name.
    names = {t.name for t in state.tables}
    assert any("macro_variables" in n or ".csv" in n for n in names)
